name: counter
description: A sample command-line application.
version: 1.0.0

publish_to: none

environment:
  sdk: '>=2.17.6 <3.0.0'

dev_dependencies:
  build_runner: ^2.3.0
  injectable_generator: ^2.1.3
  lints: ^2.0.0
  test: ^1.16.0
dependencies: {get_it: ^7.2.0, injectable: ^2.1.0}
